{"uuid": "67ba37e6-e9da-4bd2-b580-8f920b930009", "rulebook_name": "lol", "description": "Regulatory framework for lol", "file_path": "/app/code/src/data/rulebooks/67ba37e6-e9da-4bd2-b580-8f920b930009/FR_Y-14Q20240331_i-160-218.pdf", "created_at": "2025-03-25T15:05:19.512201", "file_size": 698336, "original_filename": "FR_Y-14Q20240331_i-160-218.pdf", "status": "FAILED", "rules": [], "processing_error": "Error generating rules: Task <Task pending name='Task-3' coro=<RulebookService.create_rulebook() running at /app/code/src/backend/app/services/rulebook_service.py:141> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Task pending name='Task-4' coro=<UnaryUnaryCall._invoke() running at /usr/local/lib/python3.11/site-packages/grpc/aio/_call.py:577>> attached to a different loop"}